# TASK 3
IRIS FLOWER SPECIES TEST

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

In [2]:
# importing dataset
df = sns.load_dataset("iris")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.shape

(150, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
df.describe(include="all")

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [7]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [9]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [10]:
# label encoding
df['species'].replace(["versicolor","virginica","setosa"], [0,1,2], inplace = True)

In [11]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        2
1           4.9          3.0           1.4          0.2        2
2           4.7          3.2           1.3          0.2        2
3           4.6          3.1           1.5          0.2        2
4           5.0          3.6           1.4          0.2        2

### LOGISTIC REGRESSION

In [12]:
# splitting the data
X = df.drop(['species'], axis=1).values
y = df['species'].values

In [13]:
from sklearn.linear_model import LogisticRegressionCV
# CV cross validation
# don't have to use train_test split if we use LogRegCV

In [14]:
# creating model
clf = LogisticRegressionCV(random_state=0, multi_class='multinomial')

In [15]:
# training the model
clf.fit(X,y)

C:\Users\AUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\AUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = 

LogisticRegressionCV(multi_class='multinomial', random_state=0)

In [16]:
y_pred = clf.predict(X)

In [21]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

In [18]:
metrics.confusion_matrix(y, y_pred)

array([[48,  2,  0],
       [ 1, 49,  0],
       [ 0,  0, 50]], dtype=int64)

In [19]:
metrics.accuracy_score(y_pred,y)

0.98

In [20]:
clf.score(X,y)

0.98

In [22]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97        50
           1       0.96      0.98      0.97        50
           2       1.00      1.00      1.00        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150



SACLING THE DATASET

In [23]:
# scaling the dataset
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()
x_std = scaler.fit_transform(X)

In [25]:
# training model 
# model with scaled values
model = clf.fit(x_std,y)

In [26]:
new_obs = [[.5,.5,.5,.5]]

In [27]:
# predict class
model.predict(new_obs)

array([0], dtype=int64)

In [28]:
model.predict_proba(new_obs)

array([[9.70140320e-01, 2.92634349e-02, 5.96244929e-04]])

In [29]:
y1_pred = model.predict(x_std)

In [30]:
metrics.accuracy_score(y,y1_pred)

0.98

using train_test_split

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1, test_size=0.3)

In [32]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0, multi_class= 'multinomial')

In [33]:
lr.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial', random_state=0)

In [34]:
yt_pred = lr.predict(X_test)

In [35]:
yt_pred

array([2, 0, 0, 2, 1, 0, 1, 2, 2, 1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0,
       1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 0, 2, 0, 1, 1, 2, 1, 1,
       0], dtype=int64)

In [39]:
log_reg_acc = metrics.accuracy_score(y_test,yt_pred)
log_reg_acc

0.9777777777777777

In [37]:
metrics.confusion_matrix(y_test,yt_pred)

array([[17,  1,  0],
       [ 0, 13,  0],
       [ 0,  0, 14]], dtype=int64)

In [38]:
print(classification_report(y_test,yt_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        18
           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



### KNN

In [46]:
iris_df = sns.load_dataset("iris")

In [47]:
input_array = ['6.4', '3', '3.8', '1.9']
type(input_array)

list

In [54]:
k1 = input('lower limit of range of k : ')
k2 = input('upper limit of range of k : ')

lower limit of range of k : 3
upper limit of range of k : 6


In [49]:
input_array

['6.4', '3', '3.8', '1.9']

In [50]:
from math import *
for index, row in iris_df.iterrows():
    eucDist = sqrt(((float(input_array[0]) - float(row['sepal_length']))**2+
                   (float(input_array[1]) - float(row['sepal_width']))**2+
                   (float(input_array[2]) - float(row['petal_length']))**2+
                   (float(input_array[3]) - float(row['petal_width']))**2))
    
    iris_df.loc[index,'distance'] = eucDist

In [51]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species  distance
0           5.1          3.5           1.4          0.2  setosa  3.254228
1           4.9          3.0           1.4          0.2  setosa  3.301515
2           4.7          3.2           1.3          0.2  setosa  3.474191
3           4.6          3.1           1.5          0.2  setosa  3.380828
4           5.0          3.6           1.4          0.2  setosa  3.312099

In [52]:
iris_df.sort_values('distance', ascending=True, inplace=True)

In [53]:
iris_df

sepal_length  sepal_width  petal_length  petal_width     species  distance
71           6.1          2.8           4.0          1.3  versicolor  0.728011
61           5.9          3.0           4.2          1.5  versicolor  0.754983
74           6.4          2.9           4.3          1.3  versicolor  0.787401
75           6.6          3.0           4.4          1.4  versicolor  0.806226
97           6.2          2.9           4.3          1.3  versicolor  0.812404
..           ...          ...           ...          ...         ...       ...
41           4.5          2.3           1.3          0.3      setosa  3.593049
38           4.4          3.0           1.3          0.2      setosa  3.624914
42           4.4          3.2           1.3          0.2      setosa  3.630427
22           4.6          3.6           1.0          0.2      setosa  3.785499
13           4.3          3.0           1.1          0.1      setosa  3.865230

[150 rows x 6 columns]

In [55]:
# select the first K rows into a new df
k = int(k1)

iris_df_k = iris_df.iloc[0:k, :].copy()

In [56]:
iris_df_k

sepal_length  sepal_width  petal_length  petal_width     species  distance
71           6.1          2.8           4.0          1.3  versicolor  0.728011
61           5.9          3.0           4.2          1.5  versicolor  0.754983
74           6.4          2.9           4.3          1.3  versicolor  0.787401

In [57]:
# drop target variable
X = iris_df.drop(['species','distance'], 1).values

y1 = iris_df['species'].values

y = iris_df['species']

In [58]:
# scaling of x
from sklearn.preprocessing import MinMaxScaler
sclr = MinMaxScaler()
sclr

MinMaxScaler()

In [59]:
X_scaled = sclr.fit_transform(X)
print('X_scaled  type is ', type(X_scaled))
X_scaled

X_scaled  type is  <class 'numpy.ndarray'>


array([[0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.36111111, 0.375     ,

In [60]:
# transform scaling data into a new dataframe
X_scaled_df = pd.DataFrame(X_scaled, columns= ['s_SepalLength',
                                              's_SepalWidth',
                                              's_PetalLength',
                                              's_PetalWidth'])

X_scaled_df

s_SepalLength  s_SepalWidth  s_PetalLength  s_PetalWidth
0         0.500000      0.333333       0.508475      0.500000
1         0.444444      0.416667       0.542373      0.583333
2         0.583333      0.375000       0.559322      0.500000
3         0.638889      0.416667       0.576271      0.541667
4         0.527778      0.375000       0.559322      0.500000
..             ...           ...            ...           ...
145       0.055556      0.125000       0.050847      0.083333
146       0.027778      0.416667       0.050847      0.041667
147       0.027778      0.500000       0.050847      0.041667
148       0.083333      0.666667       0.000000      0.041667
149       0.000000      0.416667       0.016949      0.000000

[150 rows x 4 columns]

In [61]:
y.head()

71    versicolor
61    versicolor
74    versicolor
75    versicolor
97    versicolor
Name: species, dtype: object

In [62]:
df_iris_scaled = pd.concat([X_scaled_df,y], axis= 1)
df_iris_scaled.head()

s_SepalLength  s_SepalWidth  s_PetalLength  s_PetalWidth species
0       0.500000      0.333333       0.508475      0.500000  setosa
1       0.444444      0.416667       0.542373      0.583333  setosa
2       0.583333      0.375000       0.559322      0.500000  setosa
3       0.638889      0.416667       0.576271      0.541667  setosa
4       0.527778      0.375000       0.559322      0.500000  setosa

In [63]:
# importing kNN
from sklearn.neighbors import KNeighborsClassifier

In [64]:
knc = KNeighborsClassifier(n_neighbors=5)

In [65]:
knc.fit(X_scaled,y1)

KNeighborsClassifier()

In [66]:
y_pred_knc = knc.predict(X_scaled)
y_pred_knc

array(['versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'versicolor',
       'virginica

In [68]:
# create confusion matrix

cm = confusion_matrix(y1,y_pred_knc)
cm

array([[50,  0,  0],
       [ 0, 48,  2],
       [ 0,  4, 46]], dtype=int64)

In [69]:
knn_acc = metrics.accuracy_score(y1,y_pred_knc)
knn_acc

0.96

### NAIVE BAYES

In [70]:
# importing model
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

gnb = GaussianNB()
mnb = MultinomialNB()

In [71]:
# fitting the training data
gnb_fit = gnb.fit(X_train,y_train)

In [72]:
mnb_fit = mnb.fit(X_train,y_train)

In [73]:
gnb_y_pred = gnb.predict(X_test)

In [74]:
mnb_y_pred = mnb.predict(X_test)

In [75]:
gnb_y_pred, mnb_y_pred

(array([2, 0, 0, 2, 1, 1, 1, 2, 2, 1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0,
        1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 0, 2, 0, 1, 1, 2, 0, 1,
        0], dtype=int64),
 array([2, 0, 0, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1,
        1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1,
        1], dtype=int64))

In [83]:
gnb_acc = metrics.accuracy_score(gnb_y_pred, y_test)*100
gnb_acc
#print("MultinomialNB accuracy :",metrics.accuracy_score(mnb_y_pred, y_test)*100)

93.33333333333333

In [84]:
gnb_acc

93.33333333333333

In [79]:
!pip install tabulate

In [80]:
from tabulate import tabulate

In [87]:
acc_table = [
    ["Logistic Regrression",log_reg_acc*100],
    ["kNN",knn_acc*100],
    ["Naive Bayes", gnb_acc]
]
head = ["MODEL NAME","ACCURACY SCORE(%)"]

print(tabulate(acc_table,headers=head,tablefmt="grid"))

+----------------------+---------------------+
| MODEL NAME           |   ACCURACY SCORE(%) |
+======================+=====================+
| Logistic Regrression |             97.7778 |
+----------------------+---------------------+
| kNN                  |             96      |
+----------------------+---------------------+
| Naive Bayes          |             93.3333 |
+----------------------+---------------------+
